project:
  type: book
  output-dir: docs

lang: es

book:
  title: "Introducción a Python para Ingeniería, Datos y Economía"
  author: "John Leal"
  date: today
  downloads: [pdf]
  chapters:
    - index.qmd
    - introduccion.qmd
    - fundamentos.qmd
    - control-flujo.qmd
    - estructuras-datos.qmd
    - numpy-graficas.qmd
    - pandas.qmd
    - economia-administracion.qmd
    - aplicaciones-ingenieria.qmd
    - proyectos.qmd
    - big-data.qmd
    - analisis-datos-grandes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    latex-auto-install: false
    include-in-header:
      text: |
        \usepackage{fvextra}
        \AtBeginDocument{%
          \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
            frame=single, rulecolor=\color{black!40},
            bgcolor=black!8, fontsize=\small, framesep=3mm}}
